elastic_stack_node_name: "{{ ansible_hostname }}"
elastic_stack_version: 5.6.3
xpack_archive_checksum: fa9b2b58bf7d373202f586036d4ddf760b6eeba0
xpack_archive_name: "x-pack-{{ elastic_stack_version }}.zip"
xpack_archive_path: "/tmp/{{ xpack_archive_name }}"
xpack_archive_url: "{{ repository_url_root }}/{{ xpack_archive_name }}"
