- name: Copy logstash.yml template
  notify: Restart Logstash service
  template:
    src: "{{ role_path }}/templates/etc/logstash/logstash.yml.j2"
    dest: /etc/logstash/logstash.yml
    owner: root
    group: logstash
    mode: 0660
