- name: Get multiple module stats
  stat:
    path: "{{ item.path }}"
  register: modules_stats
  with_items: "{{ modules }}"

- name: Download multiple modules
  get_url:
    url: "{{ item.item.url }}"
    dest: "{{ item.item.path }}"
  check_mode: no
  when: item.stat.exists == false or item.stat.checksum != item.item.checksum
  with_items: "{{ modules_stats.results }}"
