- name: Reload Elasticsearch daemon
  notify: Restart Elasticsearch service
  systemd:
    name: elasticsearch.service
    daemon_reload: yes

- name: Restart Elasticsearch service
  service:
    state: restarted
    name: elasticsearch
