- name: Create data directory
  file:
    state: directory
    path: "{{ elasticsearch_data_dir }}"
    owner: elasticsearch
    group: root
    mode: 0750

- name: Create templates directory
  file:
    state: directory
    path: /etc/elasticsearch/templates
    owner: root
    group: elasticsearch
    mode: 0750

- name: Create logs directory
  file:
    state: directory
    path: "{{ elasticsearch_log_dir }}"
    owner: elasticsearch
    group: root
    mode: 0750

- name: Create systemd override directory
  file:
    state: directory
    path: /etc/systemd/system/elasticsearch.service.d
    owner: root
    group: root
    mode: 0755
